class apiResources:
    login = '/auth/login/'
    clients = '/api/clients/'
    mpadaccounts = '/mpadaccounts/'
    getCampaignSetupFormConfig = '/api/experiment_setup/campaign-setup-form-config/'
    getids = '/api/experiment_setup/clients/'
    pages = '/assets/?fields=pages'
    instagram = '/assets/?fields=instagramaccounts'
    customAudience = '/assets/?fields=customaudiences'
    createExpSetup = '/create/'
    getExpSetup = '/api/experiment_setup/'
    getCreative = '/creative/'
    getAdaccount = '/adaccount/'
    experimentSetup = '/experiment_setup/'
    getCreativeFiles = '/creative_files/'
    getCreativeTemplates = '/creative_templates/'
    getPixelIDs = '/assets/?fields=pixels'
    getStoryName = '/?storyname=true'
    publish = '/publish_request/new/'

